### ISSUE TITLE
example conda environment/docker file..

### ISSUE THREAD

**Issue by yfarjoun** [RajLabMSSM/leafcutter-pipeline#7]
Hi,

I'm trying to set up a project to use the leafcutter-pipeline using docker/conda and am having trouble getting a conda environment set and get the packages to compile (on R 3.6) 

Currently I have the following in my environment: 
```yaml
channels:
  - conda-forge
  - bioconda
dependencies:
  - openjdk=8.0.152
  - bwa==0.7.17
  - samtools==1.14
  - r-base<4.0.0
  - r-essentials
  - r-rstan
  - r-remotes
  - python=3.6
  - bioconda::tabix==1.11
  - ghostscript==9.54.0
  - snakemake
  - regtools=0.5.0
```

After creating the conda environment I install the required r-packages via:
```R

install.packages("renv", repos = "https://cloud.r-project.org")
if (! "renv" %in% rownames(installed.packages())){ quit(save="no",status=1) }

remotes::install_github("stan-dev/rstantools", quiet=TRUE)
if (! "rstantools" %in% rownames(installed.packages())){ quit(save="no",status=1) }

# adds quantify PSI function
remotes::install_github("davidaknowles/leafcutter/leafcutter", ref = "psi_2019", quiet=TRUE) 
if (! "leafcutter" %in% rownames(installed.packages())){ quit(1) }

```

However, installing rstantools in this environment fails with an error I don't understand.
